config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tasks do
    resources :locations
    resources :bids
  end
  resources :charges

  get 'about/index'
  get 'search/index' => 'search#index'
  devise_for :users, controllers: { registration: 'registrations' }, controllers: { sessions: 'sessions' }, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    resources :tasks
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/task.rb
class Task < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  include PgSearch
     pg_search_scope :search,
                     against: [
                       :title,
                       :location
                     ],
                     using: {
                       tsearch: {
                         prefix: true,
                         normalization: 2
                       }
                     }
  def self.perform_search(keyword)
    if keyword.present?
    then Task.search(keyword)
    else Task.all
    end
  end


  mount_uploader :image, ImageUploader
  validates :image, presence: true
  has_many :bids, dependent: :destroy
  has_one :location, dependent: :destroy



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
      @task = Task.new(:user_id => @user)
      if params[:search].present?
      @tasks = Task.perform_search(params[:search])
      else
      @tasks = Task.all
      end

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @bids = Bid.where(task_id: @task.id).order("created_at DESC")
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to new_task_location_path(@task), notice: 'Task was successfully created.' }
        ModelMailer.send_simple_message(current_user).deliver
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due, :people, :image, :start, :location, :price)
    end


    def owned_post
      @task = Task.find(params[:id])
      unless current_user == @task.user
      flash[:alert] = "That task doesn't belong to you!"
      redirect_to tasks_path
    end
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.input :title, class: "form-control", placeholder: "Title of the task" %>
    </div>
    <div class="form-group col-md-7">
    <%= f.input :description, class: "form-control", placeholder: "Enter in details" %>
    </div>
    <div class="form-group col-md-7">
    <%= f.input :price, class: "form-control", placeholder: "Enter in a autowin price" %>
    </div>
  </div>
  <div class="bottommargin-sm col-md-6">
<%= f.input :start, as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>
  </div>
  <div class="bottommargin-sm col-md-6">
<%= f.input :due, as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%d-%m-%Y') } %>
  </div>

  <div class="form-group col-md-6">
      <%= f.input :people, class: "form-control", placeholder: "How many people needed?" %>
  </div>

  <div class="form-group col-md-12">
      <%= f.input :image, as: :file, class: "form-control-file"%>
  </div>

  <div class="form-actions col-md-12">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
</form>


<% end %>

app/views/tasks/_show-location.html.erb
<div class="container">
  <div class="row">

    <div class="task-details well col-md-10">
    <h1>Task Name</h1>
    <p><%= @task.title %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Task Description</h1>
    <p><%= @task.description %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Start</h1>
    <p><%= @task.start %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Due</h1>
    <p><%= @task.due %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>How many people is needed</h1>
    <p><%= @task.people %></p>
    </div>

  </div>

</div>

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, class: 'btn btn-primary', style: 'color: #fff;' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Create a Task
  <% end %>
  <h1>Tasks Available</h1>
</div>
    <% @tasks.each do |task| %>
      <%= content_tag :tr, id: dom_id(task), class: dom_class(task) do %>    <div class="col-sm-3">
        <div class="div2">
          <div class="div10">
            <div id="DIV_1" style="width: 33.3%;, float: left;", class="display:inline-block;">
              <div id="DIV_2">
                <div id="DIV_3">
                  Task
                </div> <% @location = Location.find(task.location.id) %> <%= link_to image_tag(task.image_url(:thumb), :width => 355, :height => 235),task_location_path(task,@location) %>
                <div id="DIV_6">
                  $<%= task.price %><span id="SPAN_7">Autowin</span>
                </div>
              </div>
              <div id="DIV_13">
                <h3 id="H3_14">
                  <a href="#" id="A_15"><%= task.title %></a>
                  <div class="line" style="margin-top: 15px; margin-bottom: 15px;"></div>
                  <div class="row no-gutters box-arthur">
                    <div class="col-lg-6 arthur-box-inner">Start:<pre><%= task.start %></div>
                    <div class="col-lg-6 arthur-box-inner">Due:<pre><%= task.due %></div>
                    <div class="col-lg-6 arthur-box-inner">People:<pre><%= task.people %></div>
                <% if current_user == @task.user %>
                  <% else %>
                  <div class="col-lg-6 arthur-box-inner" style="font-size: 15px;"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
                  <% end %>

              </div>
            </div>
          </div>
        </div>
    </div>






<% end %>
<% end %>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h3>Create a Task</h3>
  <h2>Let the community help you.</h2>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, class: 'btn btn-default' do %>
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
<% end %>
<%= link_to edit_task_path(@task), class: 'btn btn-primary' do %>
<span class="glyphicon glyphicon-pencil"></span>
Edit
<% end %>
<h1>Show task</h1>
</div>

<dl class="dl-horizontal">
<dt>Image:</dt>
<dd><%= image_tag @task.image.url%></dd>
</dl>

<section class="task-show">

<div class="col-md-6 col-md-offset-1">


<div class="container">
  <div class="row">

    <div class="task-details well col-md-10">
    <h1>Task Name</h1>
    <p><%= @task.title %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Task Description</h1>
    <p><%= @task.description %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Start</h1>
    <p><%= @task.start %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>Due</h1>
    <p><%= @task.due %></p>
                			<div class="divider"><i class="fas fa-cloud"></i></div>
    <h1>How many people is needed</h1>
    <p><%= @task.people %></p>
    </div>

  </div>

</div>


</div>

</section>