config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tasks do
    resources :locations
    resources :bids
  end
  resources :charges

  get 'about/index'
  get 'search/index' => 'search#index'
  devise_for :users, controllers: { registration: 'registrations' }, controllers: { sessions: 'sessions' }, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    resources :tasks
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
  belongs_to :task
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
before_action :set_location, only: [:show, :edit, :update, :destroy]
before_action :set_task, only:[:new, :create]


  def index
    @task = Task.find(params[:task_id])
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => 'distance')
    else
      @locations = Location.all
    end
  end

  def show
    @task = Task.find(params[:task_id])
    # @location = Location.find(params[:id])
    @bids = Bid.where(task_id: @task.id).order("created_at DESC")
  end

  def new
    @location = Location.new
  end

  def edit
  end

  def create
    @task = Task.find(params[:task_id])
    @location = Location.new(allowed_params)
    @location.task_id = @task.id

    if @location.save
      redirect_to task_location_path(@task,@location), :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    # @location = Location.find(params[:id])
  end

  def update
    @task = Task.find(params[:task_id])
    # @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to task_location_path(@task,@location), :notice  => "Successfully updated location but please check your address if it's correct."
    else
      render :edit
    end
  end

  def destroy
    # @location = Location.find(params[:id])
    @location.destroy

    redirect_to task_locations_url, :notice => "Successfully destroyed location."
  end

  private
  def set_location
    @location = Location.find(params[:id])
  end

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for([@task, @location]) do |f|  %>

<p>
  <%= f.label :address %><br />
  <%= f.text_field :address %>
</p>
<p>
  <%= f.label :latitude %><br />
  <%= f.text_field :latitude %>
</p>
<p>
  <%= f.label :longitude %><br />
  <%= f.text_field :longitude %>
</p>
<p><%= f.submit %></p>


<% end %>

app/views/locations/_update-form.html.erb
<%= simple_form_for([@task, @location]) do |f|  %>

          <form>
            <div class="form-group col-md-7">
              <label for="inputAddress">Update Address</label>
              <%= f.text_field :address, :id => "inputAddress", :class => "form-control", :placeholder => "1234 Main St" %>
            </div>
            <div class="form-group">
            </div>
            <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Address</button>
            </div>
          </form>

          <% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", task_location_path %> |
  <%= link_to "View All", task_locations_path %>
</p>

app/views/locations/edit_html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<%= form_tag task_locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", task_location_path(@task,location) %></td>
      <td><%= link_to "Edit", edit_task_location_path(@task,location) %></td>
    </tr>

  <% end %>
</table>

<p><%= link_to "New Location", new_task_location_path %></p>

app/views/locations/new.html.erb
<%= render 'form' %>
<p><%= link_to "Back to List", task_locations_path %></p>

app/views/locations/show.html.erb
					<div class="sidebar nobottommargin col_last clearfix well">
						<div class="sidebar-widgets-wrap">

							<div class="widget clearfix">

								<h4>Location</h4>
								<div id="post-list-footer">

									<div class="spost clearfix">
										<div class="entry-c">
											<div class="entry-title">
                        <% if @location.nearbys(20) != nil %>
                      <% for location in @location.nearbys(20) %>
                        <li><%= link_to location.address, task_location_path %> (<%= location.distance.round(2) %> miles) - This task is near you</li>
                      <% end %>
                      <%else%>
                      <li>nothing here</li>
                      <%end%>
											</div>
										</div>
									</div>

									<div class="spost clearfix">
										<div class="entry-c">
											<div class="entry-title">
                        <% @locations.blank? || @task.user_id == current_user.id %>
                        <%= render 'locations/update-form' %>
											</div>
										</div>
									</div>

								</div>

							</div>
                            </div>
                                          </div>
              <div class="container">

              <div class="row">

                <section id="content">

                			<div class="content-wrap">

                				<div class="container clearfix">

                					<div class="postcontent nobottommargin">

                						<div id="posts" class="events small-thumbs">



                							<div class="entry clearfix">
                								<div class="entry-image">
                									<a href="#">
                										<%= image_tag @task.image_url %>
                										<div class="entry-date"><span><%= time_ago_in_words @task.created_at %></span></div>
                									</a>
                								</div>
                								<div class="entry-c">
                									<div class="entry-title">
                										<h2><a href="#"><%= @task.title %></a></h2>
                									</div>
                									<ul class="entry-meta clearfix">
                										<li><span class="badge badge-danger">People: <%= @task.people %></span></li>
                										<li><a href="#"><i class="icon-time"></i> <%= @task.start %> - <%= @task.due %></a></li>
                										<li><a href="#"><i class="icon-map-marker2"></i> <%= @location.address %></a></li>
                									</ul>
                									<div class="entry-content">
                										<p><%= @task.description %></p>
                                    <p><%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@location.latitude},#{@location.longitude}&markers=#{@location.latitude},#{@location.longitude}&zoom=14&size=640x400&key=#{Rails.application.credentials.google_map[:api_key]}",
                                                                              class: 'img-fluid img-rounded'%></p>
                                    <%= link_to "Edit", edit_task_location_path(@location) %> |
                                    <%= link_to "Destroy", task_location_path, :confirm => 'Are you sure?', :method => :delete %> |
                                    <%= link_to "View All", tasks_path %>
                									</div>
                								</div>


                							</div>

                						</div>
              <div class="col-md-12 well">


              <% unless @bids.where("user_id = ?", current_user.id).exists? %>
              <p>Hi, if you would like to bid. Click on the bid button below.</p>
              <%= link_to "Bid Task", new_task_bid_path(@task,:location_id => @location.id), class: "btn btn-danger" %>

              <% end %>
                <% @bids.each do |bid| %>
              <div class="entry clearfix">
                <div class="entry-c">
                  <div class="entry-title">
                    <h2><a href="#"><%= bid.name %></a></h2>
                  </div>
                  <ul class="entry-meta clearfix">
                    <li><span class="badge badge-danger"><h3>$<%= bid.offer %></h3></span></li>
                    <li><a href="#"><i class="icon-time"></i> <%= bid.name.capitalize %> </a></li>
                    <li><a href="#"><i class="icon-map-marker2"></i> Bid created <%= time_ago_in_words bid.created_at %></a></li>
                  </ul>
                  <div class="entry-content">
                    <p><%= bid.comment %></p>
                  </div>
                  <% if @task.user_id == current_user.id %>
                  <%= link_to "Accept Offer", new_charge_path(:bid_id => bid.id), class: "btn btn-default" %>
                  <% end %>
                </div>
              </div>
              <% end %>

              <div class="row mb-3">
                <div class="col-12">
                  <a href="#" class="btn btn-outline-secondary float-left">&larr; Older</a>
                  <a href="#" class="btn btn-outline-dark float-right">Newer &rarr;</a>
                </div>
              </div>




              </div>



		</section><!-- #content end -->