config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :tasks do
    resources :locations
    resources :bids
  end
  resources :charges

  get 'about/index'
  get 'search/index' => 'search#index'
  devise_for :users, controllers: { registration: 'registrations' }, controllers: { sessions: 'sessions' }, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    resources :tasks
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/views/layouts/_log-in.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= f.error_notification %>
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        Login
      </div>
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
            <%= f.input :email, required: true, autofocus: true, label: false, placeholder: 'Enter email', input_html: { class: 'input-md', id: 'usrname' } %>
          </div>
          <div class="form-group">
            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
            <%= f.input :password, required: true, autofocus: true, label: false, placeholder: 'Enter password', input_html: { class: 'input-md', id: 'usrname' } %>
          </div>
          <div class="checkbox">
            <label><%= f.input :remember_me, as: :boolean, style: 'margin: 0px;' if devise_mapping.rememberable? %></label>
          </div>
          <button type="submit" class="btn btn-default btn-success btn-block button-unique"><span class="glyphicon glyphicon-off"></span> Login</button>
        </form>
        <br>
        <%= button_to user_google_oauth2_omniauth_authorize_url(), class: 'btn btn-default btn-success btn-block button-unique' do %>
        Sign In With Google <i class="fab fa-google"></i>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-default btn-default pull-left button-unique" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>Cancel</button>
        <%= f.button :submit, "Log in", class: 'btn btn-default btn-default pull-left button-with-image button-unique' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px; background-color: #0092E7; border: 0;">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
<%= link_to image_tag("6.png", alt: "GigHelp", :size => "70x70", :crop => :fill), class: "navbar-brand" %>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About GigHelp", about_index_path %></li>
    <% if user_signed_in? %>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Account", edit_user_registration_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <%= render 'layouts/log-in' %>
    <li><button type="button" class="btn btn-default btn-sm" id="myBtn">Login</li>
  </ul>
      <% end %>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GigHelp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag("/stylesheets/style.css") %>
    <%= stylesheet_link_tag("/stylesheets/travel.css") %>
    <%= stylesheet_link_tag("/stylesheets/ollie.css") %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="http://fonts.googleapis.com/css?family=Poppins:300,400,400i,600,700|Montserrat:400,700|Merriweather" rel="stylesheet" type="text/css">
  </head>

  <body>
    <%= bootstrap_flash %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <script>
      $(document).ready(function () {
        $("#myBtn").click(function () {
          $("#myModal").modal();
        });
      });
    </script>
    <script type="text/javascript">
      $(document).ready(function () {
        $('.datepicker').datepicker();
      });
    </script>

  </body>
</html>